# Generated by Django 2.2.6 on 2019-11-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191116_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='acitve',
            new_name='active',
        ),
    ]
